features:
  name: false
  slogan: false
  node_user_picture: true
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
logo:
  use_default: false
  path: 'public://images/natepennington-logo.png'
favicon:
  use_default: false
  path: 'public://favicon.ico'
  mimetype: image/vnd.microsoft.icon
