palette:
  top: '#000000'
  bottom: '#000000'
  bg: '#ffffff'
  sidebar: '#f6f6f2'
  sidebarborders: '#f9f9f9'
  footer: '#292929'
  titleslogan: '#fffeff'
  text: '#3b3b3b'
  link: '#0071B3'
logo: 'public://color/bartik-278adbdf/logo.svg'
stylesheets:
  - 'public://color/bartik-278adbdf/colors.css'
files:
  - 'public://color/bartik-278adbdf/logo.svg'
  - 'public://color/bartik-278adbdf/colors.css'
