module:
  admin_toolbar: 0
  auto_entitylabel: 0
  automated_cron: 0
  big_pipe: 0
  block: 0
  block_class: 0
  block_content: 0
  bootstrap_layouts: 0
  bootstrap_library: 0
  breakpoint: 0
  ckeditor: 0
  coffee: 0
  color: 0
  comment: 0
  config: 0
  config_update: 0
  config_update_ui: 0
  contact: 0
  context: 0
  context_ui: 0
  contextual: 0
  ctools: 0
  ctools_block: 0
  ctools_views: 0
  datetime: 0
  dblog: 0
  devel: 0
  dynamic_page_cache: 0
  editor: 0
  entity: 0
  exclude_node_title: 0
  features: 0
  features_ui: 0
  field: 0
  field_collection: 0
  field_formatter_class: 0
  field_group: 0
  field_ui: 0
  file: 0
  file_entity: 0
  filter: 0
  fontawesome: 0
  fontawesome_menu_icons: 0
  google_analytics: 0
  help: 0
  history: 0
  icon: 0
  iframe: 0
  image: 0
  imce: 0
  instagram_block: 0
  kint: 0
  layout_discovery: 0
  libraries: 0
  link: 0
  media_entity: 0
  menu_breadcrumb: 0
  menu_ui: 0
  message: 0
  metatag: 0
  metatag_favicons: 0
  metatag_twitter_cards: 0
  metatag_views: 0
  migrate: 0
  migrate_drupal: 0
  migrate_drupal_ui: 0
  migrate_plus: 0
  migrate_tools: 0
  migrate_upgrade: 0
  module_filter: 0
  node: 0
  oauth: 0
  options: 0
  page_cache: 0
  panels: 0
  path: 0
  quickedit: 0
  rdf: 0
  responsive_image: 0
  responsive_menu: 0
  search: 0
  semanticviews: 0
  shortcut: 0
  site_settings: 0
  soundcloudfield: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  twitter: 0
  twitter_block: 0
  update: 0
  user: 0
  video_embed_field: 0
  video_embed_media: 0
  video_embed_wysiwyg: 0
  views_slideshow: 0
  views_slideshow_cycle: 0
  views_ui: 0
  webform: 0
  webform_examples: 0
  webform_image_select: 0
  webform_templates: 0
  webform_ui: 0
  yoast_seo: 0
  contribute: 1
  ds: 1
  fontyourface: 1
  menu_link_content: 1
  pathauto: 1
  webform_bootstrap: 1
  views: 10
  standard: 1000
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
  bootstrap: 0
  bootstrap_subtheme: 0
_core:
  default_config_hash: m2GVq11UAOVuNgj8x0t5fMOPujpvQQ_zxLoaly1BMEU
profile: standard
