horizontal_menu: main
horizontal_depth: 9
off_canvas_menus: Main
horizontal_wrapping_element: div
horizontal_breakpoint: wide
horizontal_media_query: '(min-width: 960px)'
include_css: false
off_canvas_position: left
off_canvas_theme: theme-dark
horizontal_superfish: false
horizontal_superfish_delay: 300
horizontal_superfish_speed: 100
horizontal_superfish_speed_out: 100
horizontal_superfish_hoverintent: true
hammerjs: false
breakpoint_css_filepath: 'public://css'
use_breakpoint: false
_core:
  default_config_hash: XSKdMLR7vuHUhp56C8BBAHX-WiKaMFwAFQsFelPjUVk
allow_admin: false
wrapper_admin: true
wrapper_theme: true
extension_keyboard: false
pagedim: pagedim
