favicon:
  mimetype: image/vnd.microsoft.icon
  path: 'public://favicon.ico'
  url: ''
  use_default: false
features:
  comment_user_picture: false
  comment_user_verification: true
  favicon: true
  node_user_picture: true
  logo: true
  name: false
  slogan: false
logo:
  path: 'public://images/natepennington-logo.png'
  url: ''
  use_default: false
_core:
  default_config_hash: 9rAU4Pku7eMBQxauQqAgjzlcicFZ2As6zEa6zvTlCB8
